# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapShopApp-User' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapShopApp-User

    pod 'FirebaseAuth'
    pod 'FirebaseCore'
    pod 'FirebaseFirestore'
    pod 'ReachabilitySwift'
    pod 'SnackBar.swift'
    pod 'GoogleSignIn'
    pod 'lottie-ios'

  target 'SnapShopApp-UserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapShopApp-UserUITests' do
    # Pods for testing
  end

end
